language: bash
services:
  - docker
cache:
  directories:
  - docker
before_install:
 - mkdir -p docker
 - if [[ -e docker/texbuilder.tar.gz  ]] ; then echo found ; gzip -dc docker/texbuilder.tar.gz | docker load ; else docker pull makisyu/texlive-2017 ; docker save makisyu/texlive-2017 | gzip > docker/texbuilder.tar.gz ; fi
script:
- docker run -v `pwd`/:/mnt/ makisyu/texlive-2017 /bin/bash -c "cd /mnt/src && make test"
- mkdir out/
- cp pdf/*.pdf out/
notifications:
  slack: ftsrg:qnSMPdAdgpSj9vVxcl2AB2qU
  on_success: change
  on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: out
  github-token: $GITHUB_TOKEN
  on:
    branch: master
